fprintf('-------------------------------------------------- \n');
fprintf('Display parameter values: \n');
fprintf('  A               %+5.3f   \n', P.A);
fprintf('  A_r             %+5.3f   \n', P.Ar);
fprintf('  A_u             %+5.3f   \n', P.Au);
fprintf('  B (h_bar)       %+5.3f   \n', P.B);
fprintf('  gamma           %+5.3f   \n', P.gamma);
fprintf('  theta           %+5.3f   \n', P.theta);
fprintf('  nu              %+5.3f   \n', P.nu);
fprintf('  kappa           %+5.3f   \n', P.kappa);
fprintf('  c^r             %+5.3f   \n', P.c_pt_r);
fprintf('  c^u             %+5.3f   \n', P.c_pt_u);
fprintf('  cbar (a_bar)    %+5.3f   \n', P.cbar);
fprintf('  phi             %+5.3f   \n', P.phi);
fprintf('  J               %+5.3f   \n', P.N_ind);
fprintf('  N_r             %+5.3f   \n', P.Nn_r);
fprintf('  N_u             %+5.3f   \n', P.Nn_u);
fprintf('  p_o             %+5.3f   \n', P.old);
fprintf('  omega (lambda)  %+5.3f   \n', P.omega);
fprintf('  sigma_s^H       %+5.3f   \n', P.sigma_sH);
fprintf('  sigma_h^H       %+5.3f   \n', P.sigma_hH);
fprintf('  IH_ratio        %+5.3f   \n', P.sigma_hI/P.sigma_hH);
fprintf('  mu_s^y          %+5.3f   \n', P.mu_sI_y);
fprintf('  mu_h^y          %+5.3f   \n', P.mu_hI_y);
fprintf('  zeta            %+5.3f   \n', P.zeta_tauy);
fprintf('  sigma_tau       %+5.3f   \n', P.sigma_tauy);
fprintf('  mu_r            %+5.3f   \n', P.mu_xir_y);
fprintf('  mu_u            %+5.3f   \n', P.mu_xiu_y);
fprintf('  mu_r^o          %+5.3f   \n', P.mu_xir_o-P.mu_xir_y);
fprintf('  mu_u^o          %+5.3f   \n', P.mu_xiu_o-P.mu_xiu_y);
fprintf('  sigma_xi        %+5.3f   \n', P.sigma_xir);
fprintf('  eta             %+5.3f   \n', P.mu_eta);
fprintf('  mu_varphi       %+5.3f   \n', P.mu_varphi);
fprintf('  sigma_varphi    %+5.3f   \n', P.sigma_varphi);
fprintf('-------------------------------------------------- \n');